TABLE = '''
CREATE TABLE IF NOT EXISTS TRANSACAO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TIPO INTEGER NOT NULL,
    CATEGORIA VARCHAR(40) NOT NULL,
    VALOR FLOAT NOT NULL,
    DATA DATE NOT NULL,
    DESCRICAO TEXT
);'''

FATURA_CARTAO = '''
CREATE VIEW IF NOT EXISTS FATURA_CARTAO AS
    SELECT ID, TIPO, VALOR, DATA
    FROM TRANSACAO
    WHERE CATEGORIA = "fatura";
'''

TRASACOES_POR_MES = '''
CREATE VIEW IF NOT EXISTS TRASACOES_POR_MES AS
	SELECT TIPO, STRFTIME("%Y", DATA) AS ANO, STRFTIME("%m", DATA) AS MES, SUM(VALOR)
	FROM TRANSACAO
	GROUP BY ANO, MES, TIPO;
'''

TRASACOES_POR_ANO = '''
CREATE VIEW IF NOT EXISTS TRASACOES_POR_ANO AS
	SELECT STRFTIME("%Y", DATA) AS ANO, CATEGORIA, SUM(VALOR * TIPO) 
	FROM TRANSACAO
	GROUP BY ANO, CATEGORIA;
'''