BY_ID = '''
SELECT * 
FROM TRANSACAO
WHERE ID = :id
'''

BY_YEAR = '''
SELECT STRFTIME(\"%Y\", \"DATA\") AS ANO, CATEGORIA,SUM(VALOR * TIPO) AS TOTAL
FROM TRANSACAO
WHERE ANO = :ano
GROUP BY ANO, CATEGORIA
'''

BY_MONTH = '''
SELECT STRFTIME(\"%m\", \"DATA\") AS MES, CATEGORIA,SUM(VALOR * TIPO) AS TOTAL
FROM TRANSACAO
WHERE MES = :mes
GROUP BY MES, CATEGORIA
'''