BY_ID = '''
SELECT * 
FROM TRANSACAO
WHERE ID = :id
'''

BY_YEAR = '''
SELECT STRFTIME(\"%Y\", \"DATA\") AS ANO, CATEGORIA,SUM(VALOR * TIPO) AS TOTAL
FROM TRANSACAO
WHERE ANO = :ano
GROUP BY ANO, CATEGORIA
'''

BY_MONTH = '''
SELECT STRFTIME(\"%m\", \"DATA\") AS MES, CATEGORIA,SUM(VALOR * TIPO) AS TOTAL
FROM TRANSACAO
WHERE MES = :mes
GROUP BY MES, CATEGORIA
'''

FATURA = '''
SELECT SUM(VALOR*TIPO) AS FATURA 
FROM FATURA_CARTAO;
'''

SALDO = '''
SELECT round(SUM(valor * tipo), 2) AS total
FROM TRANSACAO
WHERE NOT (CATEGORIA = 'fatura' AND TIPO = 1);
'''

DESPESAS_DO_MES = '''
SELECT 
    SUM(VALOR * TIPO) AS TOTAL,
    STRFTIME("%m", DATA) AS MES,
    STRFTIME("%Y", DATA) AS ANO
FROM TRANSACAO
WHERE (
    TIPO = -1 AND
    STRFTIME("%m", DATA) = :mes AND
    STRFTIME("%Y", DATA) = :ano)
GROUP BY ANO, MES
'''

RECEITA_DO_MES = '''
SELECT 
    SUM(VALOR * TIPO) AS TOTAL,
    STRFTIME("%m", DATA) AS MES,
    STRFTIME("%Y", DATA) AS ANO
FROM TRANSACAO
WHERE (
    TIPO = 1 AND
    STRFTIME("%m", DATA) = :mes AND
    STRFTIME("%Y", DATA) = :ano AND
    CATEGORIA != 'fatura'
) GROUP BY ANO, MES
'''